wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1697808900.926516
    t:
      1:
      - 1
      - 55
      - 100
      2:
      - 1
      - 55
      - 100
      3:
      - 23
      4: 3.11.4
      5: 0.15.12
      8:
      - 5
      13: linux-x86_64
